package evenfibonaccinumbers;
public class EvenFibonacciNumbers {public static void main(String[] args) {
       
    /*Each new term in the Fibonacci sequence is generated by adding the previous two terms.
    By starting with 1 and 2, the first 10 terms will be: 1,2,3,5,8,13,21,34,55,89,...
    By considering the terms in the Fibonacci sequence whose values do not exceed four million,
    find the sum of the even-valued terms.*/
    /*Fibonacci dizisindeki her yeni terim, önceki iki terimin toplanmasıyla oluşturulur.
    1 ve 2 ile başlayarak, ilk 10 terim şöyle olacaktır: 1,2,3,5,8,13,21,34,55,89,... 
    Fibonacci dizisinde değerleri dört milyonu aşmayan terimleri göz önünde bulundurarak,
    çift değerli terimlerin toplamını bulunuz.*/
    
    int bas=1;
    int son=1;
    int sonuc;
    int toplam=0;
        System.out.print("1,");
        for (int i = 1; i < 50; i++) {
            sonuc=bas+son;
            if (sonuc<4000000) {
             if (sonuc%2==0) {
              toplam+=sonuc;   
            }
            bas=son;
            son=sonuc;
            System.out.print(sonuc+",");   
            }
        }
        System.out.println("\nÇift değerli terimlerin toplamı: "+toplam);
    }
    
}
